name: cicd-workflow with slack integration
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - uses: act10ns/slack@v2
      with:
        channel: '#devops'
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
